{
  "name": "retry-promise-func",
  "version": "1.0.0",
  "description": "retry-promise-func是一个用于在失败时重试Promise调用的工具。",
  "main": "./lib",
  "scripts": {
    "build": "rollup -c",
    "clean": "rm -rf lib",
    "prepare": "npm run clean && npm run build",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "retry-promise-func",
    "retry-promise",
    "promise",
    "retry"
  ],
  "type": "module",
  "author": "caohuiboss",
  "license": "ISC",
  "dependencies": {
    "@babel/preset-env": "^7.20.2",
    "@babel/preset-typescript": "^7.18.6",
    "@rollup/plugin-node-resolve": "^15.0.1",
    "rollup": "^3.15.0",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-dts": "^5.2.0",
    "rollup-plugin-terser": "^7.0.2",
    "typescript": "^4.9.5"
  },
  "devDependencies": {
    "@rollup/plugin-typescript": "^11.0.0",
    "tslib": "^2.5.0"
  }
}
